### ISSUE TITLE
out of date and no longer works?

### ISSUE THREAD

**Issue by laoshaw** [ytang/mdn-cli#1]
tried a few keywords and there are no output generated, request is deprecated and no longer works

**Comment by ianchanning** [comment]
@laoshaw 

If I try installing this on Ubuntu I no longer get any output either.

It might be because the library uses <http://mdn.io> instead of <https://mdn.io>.

Anyway I switched to adding a function to my `.bashrc`:

``` bash
function mdn() {
    open https://mdn.io/$1
}
export -f mdn
```

This works in a similar way `mdn map` will open a browser to the same place as this library.

**Comment by laoshaw** [comment]
thanks but the point here is "cli", i.e. inside terminal.

**Comment by ianchanning** [comment]
@laoshaw - see my PR - that works at least for me. Code is a mess, but is a first version to get it working. See if it works for you (min Node v16). I'll try to clean up the code later.

**Comment by ytang** [comment]
@ianchanning Thanks a lot for the PR! This was some random code that I wrote and forgot eight years ago. It's nice to see someone still using and fixing it.

**Comment by laoshaw** [comment]
yes it now displays inside the terminal :)

could be nice if it can page the output with syntax highlighted, I tried to pipe output to less and bat, syntax highlight was lost.

**Comment by ytang** [comment]
@laoshaw Just pushed a change, and now you can specify `--color` to enable color forcefully.

**Comment by laoshaw** [comment]
color indeed works now, but, it's paged one line instead of one page using either less or bat when hitting enter or spacebar key. Thanks!

**Comment by ytang** [comment]
@laoshaw Hitting <kbd>enter</kbd> is supposed to scroll forward one line, whereas hitting <kbd>space</kbd> is supposed to scroll forward one screen. It might be a misconfiguration of your `less` if it didn't work this way.

**Comment by laoshaw** [comment]
you're right, I aliased my less command. Thanks!

**Comment by ianchanning** [comment]
@laoshaw @ytang I've now cleaned up my code and submitted a new PR. There is an issue with the `<code>` formatting as MDN has changed their styles - I'll raise a separate issue for that.

**Comment by ytang** [comment]
@ianchanning Much appreciated!

**Comment by ytang** [comment]
@laoshaw @ianchanning Thanks for rekindling the project! I've made a few updates and pushed a new version to `npm`. I'll stop working on it for now, but please feel free to make changes, and I'll merge the PRs.
